### ISSUE TITLE
Nerd font icons too small / not centered in "complete"

### ISSUE THREAD

**Issue by charlesroper** [adam7/delugia-code#53] opened 2021-02-28 02:58 UTC
First let me say what an brilliant project - so useful! I was previously using the Nerd Font version of Cascadia and it was getting pretty old (2007.01 I think, which is from June last year and has been updated several times since).

The issue I want to report is that the icons appear too small in Delugia Nerd Font Complete. I _almost_ ditched it completely to go back to the NF version, but thought I'd check for closed issues first. I found #31 which gave me the clue to try the Book version. This looks fine although icons sit a bit high perhaps - could do with aligning to center line rather than top?

Perhaps mention use of book for more usefully sized icons in the installation instructions?

**Screenshots**:

![delugia-complete](https://user-images.githubusercontent.com/176/109406083-1c1da380-796e-11eb-8abd-4fc5e61cd849.png)

![delugia-book](https://user-images.githubusercontent.com/176/109406085-25a70b80-796e-11eb-9437-0ac992bd25a2.png)

**Icons too high**:

![delugia-book-high](https://user-images.githubusercontent.com/176/109406334-07daa600-7970-11eb-9aa8-3fa3d7fd9b95.png)

**Visually adjusted manually** - this is about where I think they should be:

![delugia-book-center](https://user-images.githubusercontent.com/176/109406338-132dd180-7970-11eb-9e13-5edd768f5498.png)

**Comment by charlesroper** [comment] 2021-02-28 03:05
> Perhaps mention use of book for more usefully sized icons in the installation instructions?

More useful, that is, when used for command line theming that supports icons (such as [Oh my Posh](https://ohmyposh.dev/)).

Not so useful in text editors 🙂

**Comment by Mellbourn** [comment] 2021-03-13 19:50
I hope this gets looked at. To be honest, the Complete font is not usable in its current state.
But I definitely agree that this is a brilliant project. So much fresher than the standard Nerd Fonts.

**Comment by Finii** [comment] 2021-03-13 20:57
Is this not a duplicate of #31?

Did you try what is described in https://github.com/adam7/delugia-code/issues/31#issuecomment-586984820

Thanks, Fini

**Comment by Finii** [comment] 2021-03-13 21:07
Sorry you mention that in your original post :->

I will have a look tomorrow.

**Comment by Mellbourn** [comment] 2021-03-13 21:42
I've read https://github.com/adam7/delugia-code/issues/31 more carefully now, and realize that some may prefer the very small, single character icons (I don't). 
So I guess the main problem is that Book is above center. This can be seen if you compare Book with the font you get if you `brew install font-caskaydia-cove-nerd-font`

**Comment by charlesroper** [comment] 2021-03-14 00:55
@Finii My thinking is that the book version should be mentioned in the installation instructions, especially if the intention is to use the font for CLI theming.

In forcing the icons into a mono box, it is making them too small to be useful for the CLI.

The book font’s larger but non-mono icons are much more useful for CLI theming, even though you do have to add in an extra space in places to prevent the icon overlapping with the character to its right.

Aside from that docs issue (happy to write something if it would help?), the other problem is that the book font icons ride too high as I’ve tried to illustrate in my  screenshots. I don’t know enough about font editing to know what the solution is there. I ended up switching  over the the JetBrains NF which doesn’t have the same problem - icons are nicely centered.

**Comment by Finii** [comment] 2021-03-14 09:16
@charlesroper If you can come up with any concrete change of the README, I would be glad to insert it (or create a PR).

I will have a look into JetBrains NF, useful hint, tnx.

Ah, I work on the CLI (`zsh`) all day long, and for _me_ the book face is not useful at all, because I use my editor on the command line / in the command line window (`neovim`, btw ;). But then, I do not use any of the glyphs with problems in your example (like, what is that ring? Ubuntu? and the 'git' glyph). In fact I do not even use the 'complete' version of Delugia, that might be the reason problems with other glyphs are not noticed by me.

![Untitled](https://user-images.githubusercontent.com/16012374/111061213-75bfbb00-84a2-11eb-81b0-e5a31afc8c87.png)

Lets see what we have...
`E73A` ('uniE63A' of devicons)
`23FC` ('power on-off symbol' of Power Sybols)
`0041` ('A' of Cascadia Code)
`F31B` ('ubuntu' of font logos)
`0041` ('A' of Cascadia Code)
`F31C` ('ubuntu-inverse' of font logos)

![image](https://user-images.githubusercontent.com/16012374/111063062-ff748600-84ac-11eb-8e04-3d84637d2eea.png)

**Comment by Finii** [comment] 2021-03-14 09:37
Here are the glyph sources:
![image](https://user-images.githubusercontent.com/16012374/111063698-7d865c00-84b0-11eb-8e6c-87d6a33cd666.png)

And here after scaling:
![image](https://user-images.githubusercontent.com/16012374/111063871-3e0c3f80-84b1-11eb-8fd3-463b893f2eb6.png)

Let me think a bit about the scaling ...

**Comment by Finii** [comment] 2021-03-14 10:31
Okay, here we have (from left to right):
`ordinary A` - `ubuntu now` - `ubuntu new` - `right bracket`

![image](https://user-images.githubusercontent.com/16012374/111065059-fa690400-84b7-11eb-8a0d-f17fa063e7ab.png)

The 'ring' is still a bit taller than the capital heights, but it rides on the baseline. Maybe this is a good compromise. I just changed the vertical alignment algorithm, scaling is untouched.

The vertical alignment is automatically done in `font-patcher` and I see no easy way (i.e. command line switch) to change that. The change in `font-patcher` itself is trivial for this (but of course will affect other glyphs as well). Let me stew it a bit in the back of my brain.

**Comment by Mellbourn** [comment] 2021-03-14 12:19
What is that cool program you are using to edit the glyphs?

**Comment by Finii** [comment] 2021-03-14 12:30
It's the same program we use to patch the font ... [fontforge on github](https://github.com/fontforge/fontforge).

I think I solved this, but to come up with a proper commit I need to clone `nerd-fonts` which takes ages :grimacing:

**Comment by Finii** [comment] 2021-03-14 12:42
Here what `font-patcher` does with the font-logos glyphs automatic rescaling and automatic alignment...
Top row original font, bottom row after insertion into Delugia.

![image](https://user-images.githubusercontent.com/16012374/111066418-318ee380-84bf-11eb-9937-c5e4530c86c0.png)

Maybe not what ppl would expect. This SUSE animal walked on the baseline :cry:

It is possible to add font-specific scaling rules to `font-patcher` but the font-logos goes with the defaults.

I now added a rule to `font-patcher` to handle that font hopefully better.

**Comment by Finii** [comment] 2021-03-14 13:48
Ok, here is the possible fix (bottom font):

![1](https://user-images.githubusercontent.com/16012374/111070753-69078b00-84d3-11eb-9120-f3a43ca39ecd.png)

Just scaled up therefore blurry detail:

![2](https://user-images.githubusercontent.com/16012374/111070801-a23ffb00-84d3-11eb-9ed8-2b7282aef276.png)

@charlesroper @Mellbourn Please try it out, find [here](https://github.com/Finii/delugia-code/runs/2106511302) (top right: 'artifacts'). If you think that is it, we can pull it here and make new release.

**Important** That does not fix the 'git' glyph on the far right of the original post. Please send me the unicode of that glyph, or copy and past it directly into a comment window here. Even if it is not displayed correctly I will be able to extract the code.

**Comment by Finii** [comment] 2021-03-14 14:13
Maybe its this....
FontAwesome...
left: original, right: after `font-patcher`

![image](https://user-images.githubusercontent.com/16012374/111071690-98b89200-84d7-11eb-9e72-bda49eef43bb.png)

**Comment by Mellbourn** [comment] 2021-03-14 14:33
I have tested the new artifact. To me both the size and the vertical alignment of `Complete` looks perfect now!

When I compare it with `CaskaydiaCove Nerd Font`, `Delugia` is very slightly wider. Which one is "correct" I can't tell, but they are not identical in width.

**Comment by Finii** [comment] 2021-03-14 16:13
Small interruption because of tee time here :coffee: 

Ok, fixed also the `git` text thingy:

Top: before, bottom: after

![1](https://user-images.githubusercontent.com/16012374/111075471-58addb00-84e8-11eb-9c31-b68027d693a1.png)

Detail:

![image](https://user-images.githubusercontent.com/16012374/111075431-40d65700-84e8-11eb-803f-255612c66b4b.png)

I'll create a PR now and after @charlesroper tested it successfully we can merge.

**Comment by Finii** [comment] 2021-03-14 16:16
(Secretly I believe there is a more fundamental problem with `font-patcher` but due to the number of supported output fonts it is extremely difficult to be certain a _bug_ in one font is not a _feature_ in another.)

**Comment by Finii** [comment] 2021-03-14 16:32
> difficult to be certain a _bug_ in one font is not a _feature_ in another

Ah... well... in the `monospaced` fonts, where the icons are scaled down quite a but, the previous uplifting might make sense?
Shown here the new monospaced face:

![image](https://user-images.githubusercontent.com/16012374/111075900-4cc31880-84ea-11eb-9b08-f4c170fd29e8.png)

Well, _for me_ to have the icons in the x-height (lower-case space) makes sense. Will people complain?
Others might like to have the circle centered on the `>` tip or in the middle of the `[`?

Please comment in the PR (will put a link here).

**Comment by Vovcharaa** [comment] 2021-03-14 19:57
Sauce Code Pro Semibold Nerd Font Complete Mono Windows Compatible (or any other Nerd Font I tried)
![image](https://user-images.githubusercontent.com/10946676/111082115-3c716480-850f-11eb-8b9c-934da13dfeff.png)
![image](https://user-images.githubusercontent.com/10946676/111082125-4e530780-850f-11eb-9f45-687438e48ea3.png)
![image](https://user-images.githubusercontent.com/10946676/111082129-57dc6f80-850f-11eb-9e41-b08787e96696.png)
Delugia Code from PR #54 
![image](https://user-images.githubusercontent.com/10946676/111082205-bdc8f700-850f-11eb-84ac-7af3702430af.png)
![image](https://user-images.githubusercontent.com/10946676/111082216-cb7e7c80-850f-11eb-8e2a-05ed92a2c096.png)
![image](https://user-images.githubusercontent.com/10946676/111082225-d2a58a80-850f-11eb-88a6-8fbe4cadea16.png)
Why is this happening?

**Comment by Finii** [comment] 2021-03-14 20:06
Well, I thought I explained it already in the PR description.
And you are right, and I am just preparing the commit.

I reckon you are not using the 'book' face, right? (Because if you do I need to reconsider.)

**Comment by Vovcharaa** [comment] 2021-03-14 20:11
Yes

**Comment by charlesroper** [comment] 2021-03-15 23:43
Want me to try this @Finii? Is that run ([this one](https://github.com/Finii/delugia-code/runs/2106511302)) still the latest or have you updated since then?

**Comment by Finii** [comment] 2021-03-16 08:05
At the moment I believe that there is a (fundamental) error in `font-patcher`'s `get_sourcefont_dimensions()` function.

The problem seems to be that Cascadia uses all the advanced font stuff with scaling of characters by the font engine, and that does not play too well with the assumptions about sizes that `font-patcher` has. With more 'simple' fonts that is all well.

Please be patient, I'm not that familiar with these features myself and need to do some research.

**Comment by Finii** [comment] 2021-03-16 08:39
And Cascadia has a bug (that gets us).
The 'capital A ring acute' (unicode 01fA) is too big and bleeds into the line above, here shown with `CascadiaMonoPL-Regular`:

![image](https://user-images.githubusercontent.com/16012374/111278263-a4bc6500-8639-11eb-8714-8ac454117d31.png)

If we take the bounding box of all chars to determine 'the middle' this moves us a bit too high.

And then, the font size information for Windows and Mac differ. I have never seen this in a font:

![image](https://user-images.githubusercontent.com/16012374/111279595-219c0e80-863b-11eb-9e95-b9565670b636.png)

`Win Ascent` should be equal to `HHead Ascent` and (minus)`Win Descent` equal to `HHead Descent`.

**Comment by Mellbourn** [comment] 2021-03-16 10:06
Doesn't that mean that it will be a good thing to lower the glyphs?

**Comment by Finii** [comment] 2021-03-16 10:11
From the **705** fonts files in `nerd-fonts/src/unpatched-fonts` only **44** have different sizes.

* Overpass
* Monfur
* Lekton
* RobotoMono
* Inconsolata
* CascadiaCode

WHATEVER.

Finding out why we have the difference goes back to this commit in CascadiaCode: https://github.com/microsoft/cascadia-code/commit/5795d16e36748612b726164fd8b59f3c1c8b0788

If you read the commit message it says _now we follow the Google Font design method_. Which it does not, because that explicitely states that `Win Ascend` and `HHead Ascend` have to be the same :roll_eyes: 

Let me try and fix our source font (which we touch anyhow for preparation) and see how our patched fonts look then.

**Comment by Finii** [comment] 2021-03-16 13:24
@charlesroper I create yet another PR :roll_eyes: with another approach which I believe is right now. The artifacts are [here](https://github.com/adam7/delugia-code/pull/55/checks?check_run_id=2121472135).

Any reports welcome.

**Closed** 2021-03-17 19:52 UTC

**Comment by charlesroper** [comment] 2021-03-17 20:21
It's beautiful - perfect - thank you for your efforts on this! 👍😁  

![Clipboard02](https://user-images.githubusercontent.com/176/111533008-34f3ca80-875e-11eb-8239-52e4789508a2.png)

**Comment by Finii** [comment] 2021-03-17 21:27
Without your detailed report this would not have happened :+1:
