### ISSUE TITLE
Installed as 2 different fonts

### ISSUE THREAD

**Issue by rashil2000** [adam7/delugia-code#72] opened 2021-12-05 19:32 UTC
Hey!

I used to painstakingly patch Cascadia Code manually to include Nerd glyphs, before I found this repo. Many thanks for this!

But I'm facing a similar issue that I faced with Caskaydia (nerd font version of Cascadia) - when installing, two fonts show up:

![image](https://user-images.githubusercontent.com/46838874/144760121-4fb01988-880d-4994-941d-9fa313bce452.png)

![image](https://user-images.githubusercontent.com/46838874/144760245-6f24b606-9b9b-4f31-a136-803fada25622.png)

![image](https://user-images.githubusercontent.com/46838874/144760255-5e3f933a-0fa4-4181-9f9e-dbb6eedf1727.png)

Is this expected? Shouldn't the Light variant show up along with Regular and Bold in the `Delugia` font itself?

----

For now, I manually edited family name in the font files DelugiaCompleteLight.ttf and DelugiaCompleteLight-Italic.ttf from "Delugia Light" to "Delugia" in Fontforge and then installed it to solve the issue.

![Screenshot 2021-12-06 005333](https://user-images.githubusercontent.com/46838874/144760794-ab0cea3b-cebb-4382-b712-1fefd3a3847b.png)
![Screenshot 2021-12-06 005343](https://user-images.githubusercontent.com/46838874/144760796-dcbb5d40-f685-4797-bf58-3905aa06e28f.png)

**Comment by Finii** [comment] 2021-12-06 05:42
Thanks for reporting. I can fix it for Delugia in the afternoon.

To fix it generally for `font-patcher` we need something like [#706 ](https://github.com/ryanoasis/nerd-fonts/pull/706). In fact Cascadia (and other full blown fonts) and their problems with `font-patcher` is my driver for that time consuming project.

**Comment by rashil2000** [comment] 2021-12-06 06:55
Thank you for the info!

**Comment by Finii** [comment] 2021-12-06 17:12
Well, now it is fixed.

In applications that support _Typographic Families_ they will show up as packs of 6, in 'old fashioned' applications they will show up as 6 times 4 (regular, bold, italic, bold italic) and 6 times 2 (light, light italic).

![image](https://user-images.githubusercontent.com/16012374/144890592-bce963a1-f45f-431c-9afd-cab06710292f.png)

I will upload the code and refresh the repo ... soon ;)

**Comment by rashil2000** [comment] 2021-12-06 17:16
Thanks again for the fix, and for Delugia 😅

Should I close this?

**Comment by Finii** [comment] 2021-12-06 17:19
Will be auto-closed by the merge... :-)

**Closed** 2021-12-07 11:44 UTC
Labels: confirmed

**Comment by Finii** [comment] 2021-12-07 11:57
Hmm, although this fixes it, it is not as intended, ... will push another tweak
