### ISSUE TITLE
Not working in cmder

### ISSUE THREAD

**Issue by ViceIce** [adam7/delugia-code#26] opened 2020-02-10 08:28 UTC
*Env*
win: 10 1909 18363.592
pwsh: 6.2.4
posh-git: 1.0.0-beta3
oh-my-posh: 2.0.381 (Theme Paradox)
font:  Delugia-Nerd-Font (installed with scoop)

*Windows Terminal*
![image](https://user-images.githubusercontent.com/1798109/74132575-25af5e80-4be7-11ea-85a5-52fa39ecb90e.png)

*Cmder*
![image](https://user-images.githubusercontent.com/1798109/74132635-437cc380-4be7-11ea-901c-380592f3df2a.png)

**Comment by Finii** [comment] 2020-02-10 08:40
What font are you using?
What is the expected behavior, in contrast to the displayed screenshots?

I guess you could mean the 'four horizontal bars' thing (called 'strictly equivalent') is shown with Winterm and not with Cmder.
If this is the case, please see issue #22, which is exactly about this.

**Comment by ViceIce** [comment] 2020-02-10 08:49
I used Delugia-Nerd-Font (installed with scoop).

*powershell*
![image](https://user-images.githubusercontent.com/1798109/74134278-8be9b080-4bea-11ea-9d5b-c1f3f03b6555.png)


Using Hack-NF works
*cmder*
![image](https://user-images.githubusercontent.com/1798109/74134023-0960f100-4bea-11ea-9f84-1781c1c04439.png)
*powershell*
![image](https://user-images.githubusercontent.com/1798109/74134234-6eb4e200-4bea-11ea-86f8-ac26f52861a7.png)


Maybe #22 is related.

**Comment by Finii** [comment] 2020-02-10 09:38
Oh sorry, you specified the used font in the original post. *blush*

Maybe the description in #22 is not easily understood.

- Nerd Fonts (even 'full') has no strictly-equivalent-glyph.
- Font rendering in Windows seems to be hard, some applications substitude missing glyphs by other fonts (as the font rendering should automatically), but some don't. As I usually only work on Non-Windows systems I have no specifics for the reason of that fail.

So if this is about the missing 'strictly equivalent', then sorry this can not be fixed here, because:
- Cascadia Code does not provide it
- Nerd Fonts --complete does not provide it

Anyhow, as workaround you could use the patched Cascadia Code version from Nerd Fonts: [Caskaydia Cove](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip). They must use some other additional source fonts. I did not dive into the relevant PR there.

As there is now a 'official' Nerd Fonts patched version this repository became kind of obsolete.
Note that even Microsofts Powerline version of Cascadia does not include the missing glyph.

**Comment by Finii** [comment] 2020-02-10 09:42
Forgot to mention: Caskaydia Cove Complete does include a full set of math symbols, including the strictly-equivalent.

**Comment by ViceIce** [comment] 2020-02-10 09:51
ok thanks

**Comment by ViceIce** [comment] 2020-02-10 10:04
`CascaydiaCove NF` not working either

*WinTerm*
![image](https://user-images.githubusercontent.com/1798109/74140229-fef82480-4bf4-11ea-928c-f7930abe057a.png)

*Cmder*
![image](https://user-images.githubusercontent.com/1798109/74140251-0c151380-4bf5-11ea-9391-8611bf559a6f.png)

**Comment by Finii** [comment] 2020-02-10 10:55
You are right. Again sorry, I checked Cascaydia Cove in fontforge, but it has NO math symbols at all, and I misread the placeholder images for the actual glyphs:

![image](https://user-images.githubusercontent.com/16012374/74143386-04f10400-4bfb-11ea-9b05-40974cb506e4.png)

They somehow removed glyphs from the original set?!

So this boils down to the first statement:
This is a defect/quirk of the Windows font rendering mechanism. If a glyph is not existing in the used font it should try a substitute. Obviously this works with some Windows applications (WinTerm), but not with other (Powershell).

> Anyhow, as workaround you could use the patched Cascadia Code version from Nerd Fonts: Caskaydia Cove. They must use some other additional source fonts.

Well that statement was wrong. They have no additional source fonts, and thus they do not provide the glyph in question. In fact Caskaydia is _worse_ than Delugia, as it drops glyphs of the original Cascadia font.

**Comment by Finii** [comment] 2020-02-10 11:03
As you mentioned hack. That font (unpatched, original) has the full math glyphs:

![image](https://user-images.githubusercontent.com/16012374/74144587-50a4ad00-4bfd-11ea-834e-990b544bf33e.png)

As this one glyph here seems in high demand, I will check if we can patch it over from hack to Delugia, hold on...

**Comment by ViceIce** [comment] 2020-02-10 11:08
Until then i use `Hack NF` as a workaround

**Comment by Finii** [comment] 2020-02-10 14:13
Please check the font with glyphs added from the CI output:
https://github.com/adam7/delugia-code/pull/28/checks?check_run_id=436241838
It's in the top right, 'artifacts'.

Direct link: https://github.com/adam7/delugia-code/suites/448451606/artifacts/1716969

If possible please also check in a non-monospace application like _Visual Code_ with ligatures enabled, or _Writer_ or something. Thank you.

Sometimes Windows is hard to convince a font changed. Possibly it is best to first uninstall the old Delugia and then install the new font. I never had problems with just installing over another, but other have reported issues in the past.

**Comment by ViceIce** [comment] 2020-02-10 14:34
Using the `Delugia Nerd Font Powerline` variant works now in powershell and wintem
![image](https://user-images.githubusercontent.com/1798109/74157945-7b046380-4c19-11ea-8c95-51f41e00f1b4.png)

and cmder
![image](https://user-images.githubusercontent.com/1798109/74158080-bacb4b00-4c19-11ea-9268-2d4bb80c4fcc.png)

vscode
![image](https://user-images.githubusercontent.com/1798109/74158693-ccf9b900-4c1a-11ea-88fa-4c2b6a4afde9.png)

**Comment by Finii** [comment] 2020-02-10 14:47
@torpederos Maybe you want to try out PR #28 (see instructions above) as solution for your issue #22.

**Comment by ViceIce** [comment] 2020-02-12 11:48
looks like someon has found the how to add fallback fonts
---
![image](https://user-images.githubusercontent.com/1798109/74332363-db201480-4d95-11ea-844e-ce84e8583cfa.png)

https://github.com/ryanoasis/nerd-fonts/issues/375#issuecomment-585159177

**Comment by Finii** [comment] 2020-02-12 11:56
Great! Thank you for finding that information.

But I would still include ``not identical to`` and ``strictly equivalent to`` from Hack.ttf.
We already have the neighboring ``identical to`` and so on, for me it does not make sense to not-include these often used chars. See commit message of #28.

What do you think? I would generate a Delugia release then.

**Comment by ViceIce** [comment] 2020-02-12 11:59
I would include them too, but may we can add fallback fonts registry key for missing glyphs?

**Comment by ViceIce** [comment] 2020-02-12 13:11
@Finii Question out of scope: Can we add a statement to the readme for what the differences between normal and complete font are?

**Comment by Finii** [comment] 2020-02-12 13:17
I'm not sure if a font can set a registry key.

I reckon the applications that work use the Uniscribe engine (and thus font fallback), while the others use GDI (and need the font linking registry key).

This is unfortunately not a region of my expertise.
Maybe Ryan comes up with something.

I close this now, as the original problem is solved with the new release.
Thanks for the feedback, Fini

**Closed by Finii** 2020-02-12 13:17 UTC

**Comment by Finii** [comment] 2020-02-12 13:19
Ah, about the readme: Feel free to add a pull request ;-D

I can add a link to the relevant description on the Nerd Fonts page.

**Comment by Finii** [comment] 2020-02-12 21:35
Expanded README. Hope this is what you had in mind :-)

**Comment by ViceIce** [comment] 2020-02-12 21:39
Thanks very much.

**Comment by Finii** [comment] 2020-02-13 06:34
Applications not showing fallback fonts on Windows really are problem of that Application and not of the font. Here is an example how the observed problem has been fixed by using Uniscribe instead of GDI:

https://github.com/mintty/mintty/commit/d0eed429223e87468e02f1f71cb769bf6569aa0d

One should raise issues at the respective application repositories (if available).
