### ISSUE TITLE
Back tick character causes strange behaviour

### ISSUE THREAD

**Issue by adamcarr1976** [adam7/delugia-code#17] opened 2019-10-29 09:47 UTC
When using the Delugia Nerd Font the back tick character is not displaying correctly.

This is quite apparent in JavaScript code that uses a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

const displayText = `/api/Person/${personId}`;
![image](https://user-images.githubusercontent.com/861281/67755010-4f28ed80-fa2f-11e9-90e1-ed1884b3c0a5.png)
This seems to move the back tick over the semi colon making it harder to determine if the backtick is actually present.

const displayText = someFunction(`/api/person/${personId}`);
![image](https://user-images.githubusercontent.com/861281/67755077-68319e80-fa2f-11e9-869b-2e3bcac2f89f.png)
With this issue when combined with a closing bracket the back tick is removed but the character remains when you move the cursor with the arrow keys.

**Comment by Finii** [comment] 2019-10-29 09:49
Which editor are you using?
Can you also show the font version you are using?

**Comment by Finii** [comment] 2019-10-29 10:05
Looks good in Visual Studio Code OSS, with and without _ligatures_ enabled.

![Screenshot from 2019-10-29 10-59-52](https://user-images.githubusercontent.com/16012374/67757040-5d7d0680-fa3b-11e9-82c3-d517261b2ae3.png)

I have the most recent Delugia (non-complete) installed (i.e. 1910.04.1):

![Screenshot from 2019-10-29 11-03-47](https://user-images.githubusercontent.com/16012374/67757328-e7c56a80-fa3b-11e9-88d1-99758bbd9792.png)

**Comment by adamcarr1976** [comment] 2019-10-29 10:38
Using the v1910.04.1 font 

Visual Studio 2017 (15.9.17)
Windows Terminal (0.6.2951.0)

Example from Windows Terminal
![image](https://user-images.githubusercontent.com/861281/67759918-40930400-fa38-11e9-9e6a-6c02adcdab13.png)

**Comment by adamcarr1976** [comment] 2019-10-29 10:43
Let me look at it further, as it's working fine on my laptop with Windows Terminal.

**Comment by Finii** [comment] 2019-10-29 11:02
Fine :+1: And now I also have Visual Studio 17 Community (15.9.16) on my Windows test box:

![Screenshot from 2019-10-29 11-58-45](https://user-images.githubusercontent.com/16012374/67761430-8ef9d000-fa43-11e9-8ff5-92663a6c6aff.png)

There it works okay, all fresh installed. Probably you had the old (broken) revision lurking somewhere in the depths of Windows?

If you feel this solved, maybe you can close this issue?

**Closed** 2019-10-29 11:04 UTC

**Comment by adamcarr1976** [comment] 2019-10-29 11:06
I removed the old version and installed the latest version.  I am not 100% sure if Visual Studio had picked it up.  When I unblocked the file in Explorer it all started working.  🤷‍♂

**Comment by Finii** [comment] 2019-10-29 11:10
I don't even know what _unblocking in Explorer_ means at all :-D
Fine that this seems to be solved.

The backtick is specifically patched, differently from all other glyphs, so this might have been a regression of #5
