### ISSUE TITLE
Bold characters differ between Cascadia Code PL and Delugia Nerd Font Complete

### ISSUE THREAD

**Issue by slurps-mad-rips** [adam7/delugia-code#44] opened 2020-09-23 09:49 UTC
Hello! When using the bold font for Delugia, the font is rendered extremely wrong. I've attached a comparison of this happening within gvim on Windows.

Delugia Nerd Font Complete
![image](https://user-images.githubusercontent.com/63051/93996252-e46b5980-fd46-11ea-9ffc-6ff8855a26c4.png)

Cascadia Code PL
![image](https://user-images.githubusercontent.com/63051/93996573-49bf4a80-fd47-11ea-91aa-f4e6b3859851.png)

This is as of the last two releases for Delugia. I've upgraded (and downgraded) a few times and it's a very recent change.

**Comment by Finii** [comment] 2020-09-25 10:46
Yuck! I'll investigate. Upstream (i.e. Microsoft) changed something with the weights, probably that bites us now.

**Comment by Finii** [comment] 2020-09-25 13:05
> This is as of the last two releases for Delugia.

This means 2009.14 and 2008.25 are affected, but 2007.01 not?
Or does your testing and the 2009.14 release overlap?
We needed to change something for 2007.01, so I would guess it is also affected?
And 2005.15 the last release without problems for you?

The thing is that there is no Delugia *bold*, and it is generated on the fly in a crude way by your application (gvim).
It would be interesting to see if this problem started with 2008.25 where Microsoft change the weigthing mechanics.

Maybe you can answer the Q above. I would resurrect my Windows host and install gvim then.

**Comment by slurps-mad-rips** [comment] 2020-09-25 19:14
> This means 2009.14 and 2008.25 are affected, but 2007.01 not?

I had 2007.1 installed on a linux machine at one point and it worked fine. 2005.15 was installed on macOS and also worked fine (I'm lucky to have access to the three major operating systems). After installing and testing them they do not exhibit the same issues as 2008.25. 

> The thing is that there is no Delugia bold

I had a feeling this was the case and I've been getting lucky. The weighting mechanics changing does make sense however.

**Comment by Finii** [comment] 2020-09-28 08:23
Hmm, installed gvim 8.2.0012 and can not reproduce:

Delugia 2007.01:
![gvim_2007 01](https://user-images.githubusercontent.com/16012374/94407779-2f84d280-0174-11eb-92c9-c6f934e5d771.PNG)

Delugia 2009.14
![gvim_2009 14](https://user-images.githubusercontent.com/16012374/94407795-37dd0d80-0174-11eb-94de-ea2132100e8d.png)

I use this very big font size, because I'm not on the machine and my remote access stuff renders all fonts ugly if they are small.
Do you have the issue even with font size 36 pt?

**Comment by Finii** [comment] 2020-09-28 08:28
These are the files/versions downloaded and used:

![used](https://user-images.githubusercontent.com/16012374/94408611-50015c80-0175-11eb-823e-fe8a0676a8e8.PNG)

**Comment by Finii** [comment] 2020-09-28 08:32
Text rendering is so bad on my remote session, need to use something else...

![rendering](https://user-images.githubusercontent.com/16012374/94409037-e9c90980-0175-11eb-8851-cae8a7589185.PNG)

**Comment by slurps-mad-rips** [comment] 2020-09-28 09:03
@Finii I should note I'm using the CMake syntax plugin found at [pboettch/vim-cmake-syntax](https://github.com/pboettch/vim-cmake-syntax), as the default CMake syntax highlighting in vim is not the best.


Also at 36pt font it's "diminished", but still noticeable
![image](https://user-images.githubusercontent.com/63051/94412450-a7300e80-012e-11eb-9430-c1961c3d169f.png)

**Comment by Finii** [comment] 2020-09-28 09:11
Vertical lines of **R** and **T** abviously differ at your setup while not at mine.

I will try nomachine for the remote connection and the plugin (if I can install it).

**Comment by adam7** [comment] 2020-10-06 09:11
Can you check if this is still an issue with the latest release @slurps-mad-rips

**Comment by slurps-mad-rips** [comment] 2020-12-18 09:17
@adam7 apologies for the delay, this somehow got missed in my github notifications.

Small screenshots of both vim *and* VSCode showing the behavior of the latest release. 

Vim:
![image](https://user-images.githubusercontent.com/63051/102596880-aaec8500-40ce-11eb-82f9-ccaa65e5a9bf.png)

VSCode:
![image](https://user-images.githubusercontent.com/63051/102596902-b0e26600-40ce-11eb-9ba4-00e7ffed9f66.png)

**Comment by Finii** [comment] 2021-02-15 22:31
Maybe this issue will be fixed if we release **bold** versions of the fonts, as described in https://github.com/adam7/delugia-code/issues/45#issuecomment-779474071

**Comment by jebej** [comment] 2021-05-19 15:55
I am having the same issue in VSCode with version 2102.03.1:

![image](https://user-images.githubusercontent.com/11141558/118844544-08147e80-b899-11eb-9db4-042bdc3dc677.png)

**Comment by Finii** [comment] 2021-05-21 11:48
> I am having the same issue in VSCode with version 2102.03.1:

The platform is Windows?

**Comment by jebej** [comment] 2021-05-21 12:48
> The platform is Windows?

Yes.

**Comment by Finii** [comment] 2021-07-02 06:47
I guess this can be closed? Please reopen if this is still an issue with release `v2105.24.2`.

**Closed by Finii** 2021-07-02 06:47 UTC
Labels: help wanted
